INSERT INTO Balance(id,Balance) 
    VALUES(1,1000000);

CREATE TABLE IF NOT EXISTS Balance(
id INTEGER PRIMARY KEY AUTOINCREMENT, 
Balance INTEGER DEFAULT 0 CHECK(Balance >= 0))

DROP TABLE Investments
